### PR TITLE
Remove more files from the repository

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Review by torniers — COMMENTED** [review]
Hi @fingolfin, thanks for looking at our .gitignore file. Your changes seem to remove all files from /doc, including the manual (manual.pdf) itself and its html version (chap1.html - chap5.html) as well as associated .css files. Aren't those files what this folder is for? Cheers, Stephan.

**Review by torniers — APPROVED** [review]

**Comment by fingolfin** [comment]
As a general rule of thumb (of best development practices; this is independent of GAP), generated files do not belong under version control. 

so how does one get the manual?
- as a developer using the version from git directly, just build it locally 
- as a user, you get the package via a tarball or zipfile for a release of the package, and those should contain the manual and any other "necessary" generated files. To help with this, one can use https://github.com/gap-system/ReleaseTools
- Alternatively, one may browse it on the website. Again https://github.com/gap-system/ReleaseTools together with https://github.com/gap-system/GitHubPagesForGAP helps

**Comment by fingolfin** [comment]
Regarding generated files, see also eg https://perlmaven.com/dont-keep-generated-files-in-version-control (the first relevant page google showed me, so I did not carefully check it )

**Comment by torniers** [comment]
That makes a lot of sense, thank you!

**Pull request merged**
